try i = 12 do {
    print(i)
} catch e do {
    print("err")
}